package proxy

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/afshinghezeli/weightkeep/internal/fetch"
	"github.com/afshinghezeli/weightkeep/internal/hub"
	"github.com/afshinghezeli/weightkeep/internal/ids"
	"github.com/afshinghezeli/weightkeep/internal/manifest"
	"github.com/afshinghezeli/weightkeep/internal/store"
)

// Ollama pulls GGUF models from the Hub with a Docker-registry style
// protocol: `ollama pull hf.co/org/repo:Q4_K_M` asks for
// /v2/org/repo/manifests/Q4_K_M, then each layer at
// /v2/org/repo/blobs/sha256:<digest>. The model layer is the GGUF file
// itself (its SHA-256 is the digest); the config, template and params
// layers are generated by the Hub.
//
// Pointed at weightkeep (`ollama pull 127.0.0.1:8700/org/repo:Q4_K_M
// --insecure`), manifests are relayed and cached for offline use, small
// generated blobs are kept in the store like any other blob, and the model
// layer is served from the same blob huggingface_hub and llama.cpp use.

var (
	ollamaManifestRE = regexp.MustCompile(`^/v2/([^/]+/[^/]+)/manifests/([A-Za-z0-9][A-Za-z0-9._-]{0,127})$`)
	ollamaBlobRE     = regexp.MustCompile(`^/v2/([^/]+/[^/]+)/blobs/sha256:([0-9a-f]{64})$`)
	directBlobRE     = regexp.MustCompile(`^/blobs/sha256/([0-9a-f]{64})$`)
)

// maxGeneratedBlob bounds the generated blobs we fetch whole (config,
// template, params): they are a few hundred bytes.
const maxGeneratedBlob = 16 << 20

func (s *Server) handleOllama(w http.ResponseWriter, r *http.Request) bool {
	p := r.URL.EscapedPath()
	if p == "/v2/" || p == "/v2" {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, "{}")
		return true
	}
	if m := ollamaManifestRE.FindStringSubmatch(p); m != nil {
		if ids.ValidateRepoID(m[1]) != nil {
			http.Error(w, "bad repo", http.StatusBadRequest)
			return true
		}
		s.ollamaManifest(w, r, m[1], m[2])
		return true
	}
	if m := ollamaBlobRE.FindStringSubmatch(p); m != nil {
		if ids.ValidateRepoID(m[1]) != nil {
			http.Error(w, "bad repo", http.StatusBadRequest)
			return true
		}
		s.ollamaBlob(w, r, m[1], m[2])
		return true
	}
	if m := directBlobRE.FindStringSubmatch(p); m != nil {
		s.directBlob(w, r, m[1])
		return true
	}
	return false
}

// uaClass separates clients the Hub answers differently: llama.cpp gets
// extra ggufFile/mmprojFile fields in the manifest.
func uaClass(r *http.Request) string {
	if strings.HasPrefix(r.Header.Get("User-Agent"), "llama-cpp") {
		return "llama-cpp"
	}
	return "ollama"
}

// ollamaCachePath is safe to build from request values: repoID passed
// ids.ValidateRepoID, tag matched ollamaManifestRE (no leading dot, no
// separators) and class is one of two constants.
func (s *Server) ollamaCachePath(repoID, tag, class string) string {
	parts := append([]string{s.k.Store.Root(), "ollama"}, strings.Split(repoID, "/")...)
	return filepath.Join(append(parts, tag+"."+class+".json")...)
}

func (s *Server) ollamaManifest(w http.ResponseWriter, r *http.Request, repoID, tag string) {
	cache := s.ollamaCachePath(repoID, tag, uaClass(r))
	if !s.offline {
		resp, err := s.k.Hub.Passthrough(r.Context(), http.MethodGet, r.URL.EscapedPath(), nil, r.Header)
		if err == nil {
			defer resp.Body.Close()
			body, rerr := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
			if rerr == nil && resp.StatusCode == http.StatusOK && json.Valid(body) {
				if err := writeFileAtomic(cache, body); err != nil {
					s.log.Warn("caching ollama manifest", "err", err)
				}
				// Learn the revision (small files only) so the model layer's
				// digest maps to the GGUF file when Ollama asks for it next.
				if repo, perr := hub.ParseRepo(repoID); perr == nil {
					if _, lerr := s.revision(r.Context(), repo, "main"); lerr != nil {
						s.log.Warn("learning revision for ollama", "repo", repoID, "err", lerr)
					}
				}
				serveManifestBody(w, r, body)
				return
			}
			if rerr == nil && resp.StatusCode < 500 && resp.StatusCode != http.StatusTooManyRequests {
				// A real answer (unknown tag, gated repo): relay it.
				for _, k := range []string{"Content-Type", "X-Error-Code", "X-Error-Message", "WWW-Authenticate"} {
					if v := resp.Header.Get(k); v != "" {
						w.Header().Set(k, v)
					}
				}
				w.WriteHeader(resp.StatusCode)
				_, _ = w.Write(body)
				return
			}
		}
		s.log.Warn("ollama manifest upstream failed, trying cache", "repo", repoID, "tag", tag, "err", err)
	}
	body, err := os.ReadFile(cache) //nolint:gosec // G703: see ollamaCachePath
	if err != nil {
		writeUnavailable(w, fmt.Sprintf("no cached Ollama manifest for %s:%s", repoID, tag))
		return
	}
	serveManifestBody(w, r, body)
}

func serveManifestBody(w http.ResponseWriter, r *http.Request, body []byte) {
	w.Header().Set("Content-Type", "application/vnd.docker.distribution.manifest.v2+json")
	w.Header().Set("Content-Length", strconv.Itoa(len(body)))
	w.Header().Set("X-Content-Type-Options", "nosniff")
	if r.Method == http.MethodHead {
		return
	}
	_, _ = w.Write(body) //nolint:gosec // G705: registry manifest JSON
}

// ollamaBlob answers /v2/{repo}/blobs/sha256:X. HEAD reports the size.
// GET answers 200 with a Location of /blobs/sha256/X and no body. Ollama
// follows same-host redirects and wants the last response to be a 307 to
// another host or a 200 carrying Location; it then fetches ranges from that
// URL without credentials. Everything here is one host, so it's the 200 form
// (the Hub uses the same for its small generated blobs).
func (s *Server) ollamaBlob(w http.ResponseWriter, r *http.Request, repoID, sum string) {
	size, err := s.blobSize(r.Context(), sum)
	if errors.Is(err, store.ErrNotFound) && !s.offline {
		size, err = s.fetchGeneratedBlob(r.Context(), r, repoID, sum)
	}
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			http.Error(w, "blob unknown", http.StatusNotFound)
			return
		}
		writeError(w, err)
		return
	}
	h := w.Header()
	h.Set("Docker-Content-Digest", "sha256:"+sum)
	h.Set("Accept-Ranges", "bytes")
	if r.Method == http.MethodHead {
		h.Set("Content-Length", strconv.FormatInt(size, 10))
		w.WriteHeader(http.StatusOK)
		return
	}
	h.Set("Location", "/blobs/sha256/"+sum)
	h.Set("Content-Length", "0")
	w.WriteHeader(http.StatusOK)
}

// blobSize knows a blob either because it is in the store or because a kept
// manifest lists a file with that content.
func (s *Server) blobSize(ctx context.Context, sum string) (int64, error) {
	if b, err := s.k.Store.Stat(ctx, sum); err == nil {
		return b.Size, nil
	}
	loc, err := manifest.FindBySHA256(ctx, s.k.Store, sum)
	if err != nil {
		return 0, store.ErrNotFound
	}
	return loc.File.Size, nil
}

// fetchGeneratedBlob downloads a small blob the Hub generates for Ollama
// and keeps it, verified by its digest.
func (s *Server) fetchGeneratedBlob(ctx context.Context, r *http.Request, repoID, sum string) (int64, error) {
	ctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	resp, err := s.k.Hub.GetFollow(ctx, "/v2/"+repoID+"/blobs/sha256:"+sum, r.Header)
	if err != nil {
		var he *hub.HTTPError
		if errors.As(err, &he) && he.Status == http.StatusNotFound {
			return 0, store.ErrNotFound
		}
		return 0, err
	}
	defer resp.Body.Close()
	if resp.ContentLength > maxGeneratedBlob {
		// That's a model layer we don't know from a kept revision; learn
		// the revision through a pull first.
		return 0, fmt.Errorf("blob %s is %d bytes; pull the repo first: %w", sum, resp.ContentLength, store.ErrNotFound)
	}
	b, err := s.k.Store.Put(ctx, io.LimitReader(resp.Body, maxGeneratedBlob), store.Expect{SHA256: sum})
	if err != nil {
		return 0, err
	}
	return b.Size, nil
}

// directBlob serves /blobs/sha256/X: from the store if kept, streamed from
// upstream if a kept manifest lists a file with that content.
func (s *Server) directBlob(w http.ResponseWriter, r *http.Request, sum string) {
	if s.k.Store.Has(sum) {
		f, err := s.k.Store.Open(sum)
		if err != nil {
			writeError(w, err)
			return
		}
		defer f.Close()
		w.Header().Set("Content-Type", "application/octet-stream")
		w.Header().Set("Docker-Content-Digest", "sha256:"+sum)
		http.ServeContent(w, r, "", time.Time{}, f)
		return
	}
	loc, err := manifest.FindBySHA256(r.Context(), s.k.Store, sum)
	if err != nil {
		http.Error(w, "blob unknown", http.StatusNotFound)
		return
	}
	if s.offline || !loc.File.LFS {
		writeUnavailable(w, "blob is not kept locally")
		return
	}
	repo, err := hub.ParseRepo(loc.Repo.String())
	if err != nil {
		writeError(w, err)
		return
	}
	upstream := ""
	if m, err := manifest.Load(r.Context(), s.k.Store, loc.Repo, loc.Commit); err == nil {
		upstream = m.Upstream
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Accept-Ranges", "bytes")
	s.serveFlight(w, r, fetch.Target{
		Repo: repo, Commit: loc.Commit, Path: loc.File.Path, Size: loc.File.Size,
		SHA256: sum, TreeOID: loc.File.GitSHA1, LFS: true,
	}, s.k.ClientFor(upstream))
}

func writeFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { //nolint:gosec // G703: callers pass validated paths
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil { //nolint:gosec // G703: callers pass validated paths
		return err
	}
	return os.Rename(tmp, path) //nolint:gosec // G703: callers pass validated paths
}
